### ISSUE TITLE
Not in brew

### ISSUE THREAD

**Issue by gregoriopellegrino** [yb85/scantailor-advanced-osx#1]
Hi,
how can I run this formula in brew?

**Comment by yb85** [comment]
since its experimental, it was not submitted to brew. Download the formula and run it locally : ```brew install ./scantailor.rb

**Comment by gregoriopellegrino** [comment]
It installed correctly, thanks!

**Comment by yb85** [comment]
great, i'll add it to brew since it seems to work properly

**Comment by fuzzy76** [comment]
It still isn't? How about re-opening this issue, and close it once it is in brew? That way, I can subscribe here to know when it's available.
