### ISSUE TITLE
Installation of latest release fails - use HEAD instead

### ISSUE THREAD

**Issue by cmahnke** [yb85/scantailor-advanced-osx#12]
The current master doesn't work out of the box, since there has been some change in QT. This has been already addressed upstream by the release of [2019.8.16_EA](https://github.com/4lex4/scantailor-advanced/releases/tag/2019.8.16_EA).

The current state can only be installed by passing the `--HEAD` flag like this:

```
brew install --HEAD ./scantailor.rb
```

**Comment by Kaps514** [comment]
Anyone found a solution for those running Big Sur? 
![image](https://user-images.githubusercontent.com/88849362/129238716-0edaa3fd-0240-4d6e-9eed-367fc1750fdd.png)

**Comment by Kaps514** [comment]
I'd really appreciate the help. Thanks!

**Comment by pleonard212** [comment]
You'll need to `git clone https://github.com/yb85/scantailor-advanced-osx.git`, and then change into that directory, before trying `brew install --HEAD ./scantailor.rb`.  (`scantailor.rb` is a local file, not a network-hosted formula as are most homebrew packages.)

**Comment by asterizk** [comment]
Thanks Peter! Ran into the same issue as Kaps514 and that got me around it.

**Comment by yb85** [comment]
updated the readme to reflect the issue
