### ISSUE TITLE
Output error on Homebrew Scantailor advanced. 

### ISSUE THREAD

**Issue by Skypir5** [yb85/scantailor-advanced-osx#15]
First off, let me say how grateful I am to have stumbled upon this amazing programme and the dedicated people who have put it together and continue to update and fix it. I am indebted to Digital Orientalist's guide on installing. Everything works beautifully right up until the output step. I have tried many things, including uninstalling the whole package, homebrew etc., reinstalling, going again. Thinking it had something to do with the content selector including space from off the page, I also methodically went through and ensured this wasn't the case. I've also spent a while trawling the internet to try and find 

It's quite possible (likely?) that the error occurs at the de-warping stage, which I find to be excellent and would love to be able to use! The transformation of the pages is incredible. 

This is the error message I receive: 

The action “Run Shell Script” encountered an error: “qt.qpa.fonts: Populating font family aliases took 482 ms. Replace uses of missing font family "Serif" with one that exists to avoid this cost. 
Qt Concurrent has caught an exception thrown from a worker thread.
This is not supported, exceptions thrown in worker threads must be
caught before control returns to Qt Concurrent.
libc++abi: terminating with uncaught exception of type std::invalid_argument: fillMarginsInPlace: the content area exceeds image rect.”

On a related note, could anyone enlighten me as to what "Qtcodes" are and whether I have them or need to install them or something? I've tried googling and reading a lot and still can't find a particularly straightforward explanation. The same applies to the bundler referenced on this forum. 

This [page](https://github.com/scantailor/scantailor/wiki/Building-from-Source-Code-on-Linux-and-Mac-OS-X) has info on needing QT on a mac but it installs Scan Tailor using Macports and not Homebrew.  There is also some nice help on using Scantailor experimental [here](https://diybookscanner.org/forum/viewtopic.php?t=3407), including these packages: "cmake eigen qt5 jpeg libtiff boost". No one has written about needing these for Scantailor advanced but maybe I should install them? 

I apologise in advance for not being the most savvy at running things from Terminal. I'm doing my best at trying to learn though! Many thanks in advance.

**Comment by yb85** [comment]
hi, the problem does not come from QT, the error message mentions negative margins, which were not allowed as far as 1.0.17 : 
```
libc++abi: terminating with uncaught exception of type std::invalid_argument: fillMarginsInPlace: the content area exceeds image rect.
```
It is a new feature from 1.0.18, so the last build should work for you

**Comment by Skypir5** [comment]
Hi there, I reinstalled the new version but I'm getting the same error message I'm afraid. It's all down to the de-warping feature I think. I guess it alters the margin size on one or two pages. It's a shame as the difference it makes to the book is remarkable. Nonetheless, many thanks for your help.

**Comment by yb85** [comment]
Ok ! I encourage you to file an issue on @vigri repo as it seems to be a
bug related to the dewarping function and not the packaging

To file efficiently, try to give them a Minimum working example : provide
an image and a set of parameters which trigger the issue. You may even save
it as a project and share it

**Comment by Skypir5** [comment]
Ok, will do. Thanks, pal. 

All best, 

Jack
