### ISSUE TITLE
Adding 2019.8.16 Early Access version

### ISSUE THREAD

**Issue by FurloSK** [yb85/scantailor-advanced-osx#2]
Hi, thank you so much for your work!

Would you be able to release a bundled Mojave_x64 app also for [2019.8.16 Early Access](https://github.com/4lex4/scantailor-advanced/releases/tag/2019.8.16_EA) version of the app? Thank you!

**Comment by yb85** [comment]
hi,
I don't plan to do it for pre-releases.
I added the possibility to build from the "develop" branch to the Homebrew formula, so you can build the latest version with the `--devel` flag

**Comment by yb85** [comment]
since I built it, i'ill put it in the release section

**Comment by FurloSK** [comment]
wow, thank you so much! 🤗
