### ISSUE TITLE
Scantailor icon on dock

### ISSUE THREAD

**Issue by sati-bodhi** [yb85/scantailor-advanced-osx#3]
This is a minor issue. 
As there is no Scantailor.app created upon installation, I run scantailor via command line in terminal, which calls the script `/Cellar/scantailor/1.0.16/bin/scantailor`, we end up with an alias icon on dock that looks like this: 
![image](https://user-images.githubusercontent.com/7592695/80274439-f51e9180-870c-11ea-859c-3db5013f2b2a.png)

I'd like scantailor to show its original icon when running. 

![scantailor](https://user-images.githubusercontent.com/7592695/80274486-4c246680-870d-11ea-8032-a0afb432289a.png)

**Comment by yb85** [comment]
In OS X, the icon comes from the .plist file in the .app package. 
If you want a clickable executable with an icon, you should get the .app package rather than installing via homebrew. The package is available in the "Release" section of this repository

**Comment by sati-bodhi** [comment]
I've installed other apps via homebrew, such as [briss](https://formulae.brew.sh/formula/briss) and [skim](https://formulae.brew.sh/cask/skim#default).  

![image](https://user-images.githubusercontent.com/7592695/80276723-10919880-871d-11ea-9db6-839b7a6bad8a.png)
![image](https://user-images.githubusercontent.com/7592695/80276699-f0fa7000-871c-11ea-987e-1574e9055bd0.png)

They both have special icons on the dock.
