### ISSUE TITLE
Option to automate entire process? 

### ISSUE THREAD

**Issue by sati-bodhi** [yb85/scantailor-advanced-osx#4]
When operating scantailor, the user has to manually run through each of the 6 steps in order to create the final output.  

![image](https://user-images.githubusercontent.com/7592695/80274548-da98e800-870d-11ea-8ede-f32c61965138.png)

Can there be a way to automate the entire process so that a tentative output is automatically created with one click, so that, assuming the input is consistent and settings are appropriate, the user just has to make minor adjustments at the end of the procress?

**Comment by yb85** [comment]
This repo is only for installation of scantailor on os x. The feature you request should be adressed to the scantailor-advanced repository (see link on the README file)
