### ISSUE TITLE
Error on Homebrew install Catalina

### ISSUE THREAD

**Issue by Osophoso** [yb85/scantailor-advanced-osx#7]
When installing scantailor with Homebrew I get the following error on make.  See below.

Any thoughts?

Thanks.
Opale

Last 15 lines from /Users/Opale/Library/Logs/Homebrew/scantailor/02.make:
[ 49%] Built target page_split
[ 49%] Building CXX object imageproc/CMakeFiles/imageproc.dir/ColorSegmenter.cpp.o
cd /tmp/scantailor-20200718-39857-z6nzoe/scantailor-advanced-1.0.16/build/imageproc && /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++  -DBOOST_MULTI_INDEX_DISABLE_SERIALIZATION -DBOOST_TEST_DYN_LINK -DQT_CORE_LIB -DQT_GUI_LIB -DQT_WIDGETS_LIB -I/tmp/scantailor-20200718-39857-z6nzoe/scantailor-advanced-1.0.16/. -I/tmp/scantailor-20200718-39857-z6nzoe/scantailor-advanced-1.0.16/foundation -I/tmp/scantailor-20200718-39857-z6nzoe/scantailor-advanced-1.0.16/math -I/tmp/scantailor-20200718-39857-z6nzoe/scantailor-advanced-1.0.16/interaction -I/tmp/scantailor-20200718-39857-z6nzoe/scantailor-advanced-1.0.16/zones -I/tmp/scantailor-20200718-39857-z6nzoe/scantailor-advanced-1.0.16/build -F/usr/local/opt/qt/lib -I/usr/local/opt/qt/lib/QtCore.framework/Headers -I/usr/local/opt/qt/./mkspecs/macx-clang -I/usr/local/opt/qt/lib/QtWidgets.framework/Headers -I/usr/local/opt/qt/lib/QtGui.framework/Headers -I/usr/local/opt/qt/lib/QtXml.framework/Headers -I/usr/local/opt/qt/lib/QtNetwork.framework/Headers -I/usr/local/opt/qt/lib/QtOpenGL.framework/Headers  -fPIC -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk   -std=gnu++17 -o CMakeFiles/imageproc.dir/ColorSegmenter.cpp.o -c /tmp/scantailor-20200718-39857-z6nzoe/scantailor-advanced-1.0.16/imageproc/ColorSegmenter.cpp
[ 49%] Building CXX object imageproc/CMakeFiles/imageproc.dir/ColorTable.cpp.o
cd /tmp/scantailor-20200718-39857-z6nzoe/scantailor-advanced-1.0.16/build/imageproc && /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++  -DBOOST_MULTI_INDEX_DISABLE_SERIALIZATION -DBOOST_TEST_DYN_LINK -DQT_CORE_LIB -DQT_GUI_LIB -DQT_WIDGETS_LIB -I/tmp/scantailor-20200718-39857-z6nzoe/scantailor-advanced-1.0.16/. -I/tmp/scantailor-20200718-39857-z6nzoe/scantailor-advanced-1.0.16/foundation -I/tmp/scantailor-20200718-39857-z6nzoe/scantailor-advanced-1.0.16/math -I/tmp/scantailor-20200718-39857-z6nzoe/scantailor-advanced-1.0.16/interaction -I/tmp/scantailor-20200718-39857-z6nzoe/scantailor-advanced-1.0.16/zones -I/tmp/scantailor-20200718-39857-z6nzoe/scantailor-advanced-1.0.16/build -F/usr/local/opt/qt/lib -I/usr/local/opt/qt/lib/QtCore.framework/Headers -I/usr/local/opt/qt/./mkspecs/macx-clang -I/usr/local/opt/qt/lib/QtWidgets.framework/Headers -I/usr/local/opt/qt/lib/QtGui.framework/Headers -I/usr/local/opt/qt/lib/QtXml.framework/Headers -I/usr/local/opt/qt/lib/QtNetwork.framework/Headers -I/usr/local/opt/qt/lib/QtOpenGL.framework/Headers  -fPIC -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk   -std=gnu++17 -o CMakeFiles/imageproc.dir/ColorTable.cpp.o -c /tmp/scantailor-20200718-39857-z6nzoe/scantailor-advanced-1.0.16/imageproc/ColorTable.cpp
[ 50%] Building CXX object imageproc/CMakeFiles/imageproc.dir/ImageCombination.cpp.o
cd /tmp/scantailor-20200718-39857-z6nzoe/scantailor-advanced-1.0.16/build/imageproc && /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++  -DBOOST_MULTI_INDEX_DISABLE_SERIALIZATION -DBOOST_TEST_DYN_LINK -DQT_CORE_LIB -DQT_GUI_LIB -DQT_WIDGETS_LIB -I/tmp/scantailor-20200718-39857-z6nzoe/scantailor-advanced-1.0.16/. -I/tmp/scantailor-20200718-39857-z6nzoe/scantailor-advanced-1.0.16/foundation -I/tmp/scantailor-20200718-39857-z6nzoe/scantailor-advanced-1.0.16/math -I/tmp/scantailor-20200718-39857-z6nzoe/scantailor-advanced-1.0.16/interaction -I/tmp/scantailor-20200718-39857-z6nzoe/scantailor-advanced-1.0.16/zones -I/tmp/scantailor-20200718-39857-z6nzoe/scantailor-advanced-1.0.16/build -F/usr/local/opt/qt/lib -I/usr/local/opt/qt/lib/QtCore.framework/Headers -I/usr/local/opt/qt/./mkspecs/macx-clang -I/usr/local/opt/qt/lib/QtWidgets.framework/Headers -I/usr/local/opt/qt/lib/QtGui.framework/Headers -I/usr/local/opt/qt/lib/QtXml.framework/Headers -I/usr/local/opt/qt/lib/QtNetwork.framework/Headers -I/usr/local/opt/qt/lib/QtOpenGL.framework/Headers  -fPIC -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk   -std=gnu++17 -o CMakeFiles/imageproc.dir/ImageCombination.cpp.o -c /tmp/scantailor-20200718-39857-z6nzoe/scantailor-advanced-1.0.16/imageproc/ImageCombination.cpp
make[1]: *** [filters/page_layout/CMakeFiles/page_layout.dir/all] Error 2
[ 50%] Linking CXX static library libimageproc.a
cd /tmp/scantailor-20200718-39857-z6nzoe/scantailor-advanced-1.0.16/build/imageproc && /usr/local/Cellar/cmake/3.17.3/bin/cmake -P CMakeFiles/imageproc.dir/cmake_clean_target.cmake
cd /tmp/scantailor-20200718-39857-z6nzoe/scantailor-advanced-1.0.16/build/imageproc && /usr/local/Cellar/cmake/3.17.3/bin/cmake -E cmake_link_script CMakeFiles/imageproc.dir/link.txt --verbose=1
/usr/bin/ar qc libimageproc.a  CMakeFiles/imageproc.dir/Constants.cpp.o CMakeFiles/imageproc.dir/BinaryImage.cpp.o CMakeFiles/imageproc.dir/BinaryThreshold.cpp.o CMakeFiles/imageproc.dir/SlicedHistogram.cpp.o CMakeFiles/imageproc.dir/BitOps.cpp.o CMakeFiles/imageproc.dir/SeedFill.cpp.o CMakeFiles/imageproc.dir/ConnCompEraser.cpp.o CMakeFiles/imageproc.dir/ConnCompEraserExt.cpp.o CMakeFiles/imageproc.dir/GrayImage.cpp.o CMakeFiles/imageproc.dir/Grayscale.cpp.o CMakeFiles/imageproc.dir/UpscaleIntegerTimes.cpp.o CMakeFiles/imageproc.dir/ReduceThreshold.cpp.o CMakeFiles/imageproc.dir/Shear.cpp.o CMakeFiles/imageproc.dir/SkewFinder.cpp.o CMakeFiles/imageproc.dir/OrthogonalRotation.cpp.o CMakeFiles/imageproc.dir/Scale.cpp.o CMakeFiles/imageproc.dir/Transform.cpp.o CMakeFiles/imageproc.dir/Morphology.cpp.o CMakeFiles/imageproc.dir/Binarize.cpp.o CMakeFiles/imageproc.dir/PolygonUtils.cpp.o CMakeFiles/imageproc.dir/PolygonRasterizer.cpp.o CMakeFiles/imageproc.dir/HoughLineDetector.cpp.o CMakeFiles/imageproc.dir/GaussBlur.cpp.o CMakeFiles/imageproc.dir/MorphGradientDetect.cpp.o CMakeFiles/imageproc.dir/PolynomialLine.cpp.o CMakeFiles/imageproc.dir/PolynomialSurface.cpp.o CMakeFiles/imageproc.dir/SavGolKernel.cpp.o CMakeFiles/imageproc.dir/SavGolFilter.cpp.o CMakeFiles/imageproc.dir/DrawOver.cpp.o CMakeFiles/imageproc.dir/AdjustBrightness.cpp.o CMakeFiles/imageproc.dir/SEDM.cpp.o CMakeFiles/imageproc.dir/ConnectivityMap.cpp.o CMakeFiles/imageproc.dir/InfluenceMap.cpp.o CMakeFiles/imageproc.dir/MaxWhitespaceFinder.cpp.o CMakeFiles/imageproc.dir/RastLineFinder.cpp.o CMakeFiles/imageproc.dir/ColorInterpolation.cpp.o CMakeFiles/imageproc.dir/SeedFillGeneric.cpp.o CMakeFiles/imageproc.dir/BackgroundColorCalculator.cpp.o CMakeFiles/imageproc.dir/BadAllocIfNull.cpp.o CMakeFiles/imageproc.dir/ColorSegmenter.cpp.o CMakeFiles/imageproc.dir/ColorTable.cpp.o CMakeFiles/imageproc.dir/ImageCombination.cpp.o
/usr/bin/ranlib libimageproc.a
[ 50%] Built target imageproc
make: *** [all] Error 2

Do not report this issue to Homebrew/brew or Homebrew/core!

Traceback (most recent call last):
	28: from /usr/local/Homebrew/Library/Homebrew/build.rb:202:in `<main>'
	27: from /usr/local/Homebrew/Library/Homebrew/build.rb:118:in `install'
	26: from /usr/local/Homebrew/Library/Homebrew/utils.rb:474:in `with_env'
	25: from /usr/local/Homebrew/Library/Homebrew/build.rb:123:in `block in install'
	24: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1177:in `brew'
	23: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2156:in `stage'
	22: from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/forwardable.rb:230:in `stage'
	21: from /usr/local/Homebrew/Library/Homebrew/resource.rb:81:in `stage'
	20: from /usr/local/Homebrew/Library/Homebrew/resource.rb:106:in `unpack'
	19: from /usr/local/Homebrew/Library/Homebrew/resource.rb:196:in `mktemp'
	18: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `run'
	17: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `chdir'
	16: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `block in run'
	15: from /usr/local/Homebrew/Library/Homebrew/resource.rb:197:in `block in mktemp'
	14: from /usr/local/Homebrew/Library/Homebrew/resource.rb:111:in `block in unpack'
	13: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2181:in `block in stage'
	12: from /usr/local/Homebrew/Library/Homebrew/utils.rb:474:in `with_env'
	11: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2182:in `block (2 levels) in stage'
	10: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1184:in `block in brew'
	 9: from /usr/local/Homebrew/Library/Homebrew/build.rb:152:in `block (2 levels) in install'
	 8: from /Users/Opale/scantailor-advanced-osx/scantailor.rb:30:in `install'
	 7: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2099:in `mkdir'
	 6: from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/fileutils.rb:128:in `cd'
	 5: from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/fileutils.rb:128:in `chdir'
	 4: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2100:in `block in mkdir'
	 3: from /Users/Opale/scantailor-advanced-osx/scantailor.rb:32:in `block in install'
	 2: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1977:in `system'
	 1: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1977:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2039:in `block in system': Failed executing: make (BuildError)
	5: from /usr/local/Homebrew/Library/Homebrew/brew.rb:45:in `<main>'
	4: from /usr/local/Homebrew/Library/Homebrew/brew.rb:151:in `rescue in <main>'
	3: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:414:in `dump'
	2: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:360:in `issues'
	1: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:364:in `fetch_issues'
/usr/local/Homebrew/Library/Homebrew/utils/github.rb:305:in `issues_for_formula': undefined method `full_name' for nil:NilClass (NoMethodError)

**Comment by yb85** [comment]
seems to be the same issue as #6 
transfering conversation to #6

**Comment by Osophoso** [comment]
thank you:)
