### ISSUE TITLE
Install on High Sierra 10.13.6 -- think successful. not sure.

### ISSUE THREAD

**Issue by helphelpplease** [yb85/scantailor-advanced-osx#9]
Hi, I managed to get bleeding edge scantailor advanced installed on High Sierra 10.13.6 following your install instructions (I could not get it installed on Catalina, nor the non-head release). So this is great as I can start to use on my many scans. 

brew install --HEAD ./scantailor.rb

I am not sure what the bundle does. Does it give me an application icon in my dock?  (sorry I am not technical if It is a silly question, apologises)

I then followed the instructions for Bundle, but step 2 gave message "no such file or directory". I continued.. 
Installed fish
Then
1. -MacBook-Pro:scantailor-advanced-osx author$ brew link --force qt5
Linking /usr/local/Cellar/qt/5.15.0... 510 symlinks created

2 echo 'set -g fish_user_paths "/usr/local/opt/qt/bin" $fish_user_paths' >> ~/.config/fish/config.fish
-bash: /Users/author/.config/fish/config.fish: No such file or directory

3 MacBook-Pro:scantailor-advanced-osx author$ chmod 755 bundler/scantailor_bundler.command

then in terminal I typed scantailor (while in the san tailor advanced) and a notepad icon (with an arrow) appeared in dock.  The app opens. 

Is this the expected result or am I suppose to have a proper icon in my dock?

Thankyou for any help. Apologises if I am asking very basic questions.

**Comment by yb85** [comment]
the bundler produces an *.app file in the `bundle` directory. if you run scantailor from the command line it uses the binary installed by homebrew which is not a bundled app. YOu should have the scantailor icon when you run the bundled app.

anyhow, you can check the release section for prebundled packages
